[package]
name = "LiquidityLayer"
version = "1.0.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# mainnet-1.0.0
rev = "ae1212baf8f0837e25926d941db3d26a61c1bea2"

[dependencies.Critbit]
git = "https://github.com/Origin-Byte/critbit.git"
rev = "v1.0.1-mainnet"

[dependencies.Permissions]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/permissions"
# mainnet
rev = "2a435a0194a3b62988f38de519c212c224162be2"

[dependencies.Request]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/request"
# mainnet
rev = "2a435a0194a3b62988f38de519c212c224162be2"

[dependencies.Kiosk]
git = "https://github.com/Origin-Byte/nft-protocol.git"
subdir = "contracts/kiosk"
# mainnet
rev = "2a435a0194a3b62988f38de519c212c224162be2"

[addresses]
liquidity_layer = "0x0"