name: sui-test
run-name: Testing Sui packages

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Sui SDK
        run: |
          wget -qO sui https://github.com/MystenLabs/sui/releases/download/sui-v1.0.0/sui
          chmod +x sui

      - name: Run test for all modules
        run: |
          find . -name "Move.toml" |
          while read PACKAGE; do ./sui move test -p $PACKAGE  --gas_limit 5000000000; done
